telosprotocol/TOP-chain

src/xtopcom/xmetrics/xmetrics.cpp, src/xtopcom/xmetrics/xmetrics.h, src/xtopcom/xmetrics/xmetrics_unit.h
add gauge metrics implementadd gauge metrics implement
=>  feat(metrics):add gauge metrics implement 

.github/workflows/ci.yml
github action for pull request
=> chore(build): ci for pull_request on dev/fast_sync_develop

src/xtopcom/xvledger/src/xvbindex.cpp
=> fix(blockstore): add miss ref

scripts/deploy_multi_hosts/.edge_config.json, scripts/deploy_multi_hosts/keystore/T00000LKMWBfiHPeN9TShPdB9ctLDr7mmcZa46Da, scripts/deploy_multi_hosts/keystore/T00000LKy8CAPRETJmUr9DZiwCPcc9VFqDBpQEG6, scripts/deploy_multi_hosts/keystore/T00000LLLK8teSrpbtcVnaYCtykniJHHeMZegQMU, scripts/deploy_multi_hosts/keystore/T00000LPjk6KqsnCu46kHffttVPjToRmitpStvvo, scripts/deploy_multi_hosts/keystore/T00000LQkSo2PYR7hVxZmkQphvsxAbiB8V22PwPT, scripts/deploy_multi_hosts/keystore/T00000LRauRZ3SvMtNhxcvoHtP8JK9pmZgxQCe7Q, scripts/deploy_multi_hosts/keystore/T00000LRc5LxEXVdUuFcoLezjPiMw4CLYgvkEmtC, scripts/deploy_multi_hosts/keystore/T00000LcxcHVTKki5KqCKmX5BbbMSGrUPhTEpwnu, scripts/deploy_multi_hosts/keystore/T00000LfazE9WjtUu4xx5caD9w9dWwiRGggHxxvo, scripts/deploy_multi_hosts/keystore/T00000LfyErVp716mVR89UdJMQaZJ6W9Hv7NsHT4, scripts/deploy_multi_hosts/keystore/T00000LhPZXie5GqcZqoxu6BkfMUqo7e9x1EaFS6, scripts/deploy_multi_hosts/keystore/T00000Lhj29VReFAT958ZqFWZ2ZdMLot2PS5D5YC, scripts/deploy_multi_hosts/run.sh, scripts/deploy_multi_hosts/topo.json
=> add deploy_multi_hosts

src/xtopcom/xdata/xtablestate.h, src/xtopcom/xrpc/xgetblock/get_block.cpp, src/xtopcom/xrpc/xgetblock/get_block.h, src/xtopcom/xvledger/xaccountindex.h
=> feat(grpc): add interface getLatestFullBlock

src/xtopcom/xblockstore/src/xvunithub.cpp
=> bug(blockstore): top-3616, topio querytx update

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvblockhub.h, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xblockstore/src/xvunithub.h, src/xtopcom/xvledger/xvblockstore.h, tests/mock/xdatamock_table.hpp, tests/xblockstore2_test/test_block_connected.cpp
=> feat(blockstore): add get_latest_committed_full_block

src/xtopcom/xblockmaker/src/xblockmaker_face.cpp
fix(blockmaker): move xerror to xwarn
=>  fix(blockmaker): move xerror to xwarn

src/libraries/xsync/src/xchain_downloader.cpp, src/libraries/xsync/src/xsync_handler.cpp, src/libraries/xsync/src/xsync_on_demand.cpp, src/libraries/xsync/src/xsync_store.cpp, tests/mock/xmock_nodesrv.hpp, tests/xsync/test_xsync_behind_checker.cpp, tests/xsync/test_xsync_chain.cpp, tests/xsync/test_xsync_cross_cluster_chain_state.cpp
=> [bug] fail to get_latest_end_block

src/xtopcom/xbasic/src/xchain_error.cpp, src/xtopcom/xbasic/src/xthrow_error.cpp, src/xtopcom/xbasic/xerror/xchain_error.h, src/xtopcom/xbasic/xerror/xthrow_error.h, src/xtopcom/xbasic/xerror/xthrow_exception.hpp, src/xtopcom/xblockmaker/src/xunit_builder.cpp, src/xtopcom/xblockmaker/xunit_builder.h, src/xtopcom/xcommon/src/xaddress.cpp, src/xtopcom/xcommon/src/xaddress_error.cpp, src/xtopcom/xcommon/xaddress_error.h, src/xtopcom/xcontract_common/src/xcontract_state.cpp, src/xtopcom/xcontract_common/src/xproperty_access_control.cpp, src/xtopcom/xcontract_common/xcontract_state.h, src/xtopcom/xcontract_common/xproperties/xproperty_access_control.h, src/xtopcom/xcontract_runtime/src/xaccount_vm.cpp, src/xtopcom/xcontract_runtime/src/xtop_action_generator.cpp, src/xtopcom/xcontract_runtime/src/xuser_action_runtime.cpp, src/xtopcom/xcontract_runtime/xaccount_vm.h, src/xtopcom/xelection/src/xcluster_element.cpp, src/xtopcom/xelection/src/xdata_accessor_error.cpp, src/xtopcom/xelection/src/xgroup_element.cpp, src/xtopcom/xelection/src/xnetwork_element.cpp, src/xtopcom/xelection/src/xzone_element.cpp, tests/xelection/xmocked_vnode_service.h
1. put error/exception related files into xerror folder.
2. add tx execution result process logic
=> feat(xerror): unify exception utility folder locations

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvblockhub.h, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xblockstore/src/xvunithub.h, src/xtopcom/xdata/src/xlightunit.cpp, src/xtopcom/xdata/xlightunit.h, src/xtopcom/xrpc/xgetblock/get_block.cpp, src/xtopcom/xtxpool_service_v2/src/xtxpool_service.cpp, src/xtopcom/xvledger/src/xvdbkey.cpp, src/xtopcom/xvledger/src/xvledger.cpp, src/xtopcom/xvledger/src/xvstoreimp.cpp, src/xtopcom/xvledger/src/xvtransaction.cpp, src/xtopcom/xvledger/src/xvtxindex.cpp, src/xtopcom/xvledger/test/xstate_sample.cpp, src/xtopcom/xvledger/xvbindex.h, src/xtopcom/xvledger/xvblock.h, src/xtopcom/xvledger/xvblockstore.h, src/xtopcom/xvledger/xvdbkey.h, src/xtopcom/xvledger/xvdbstore.h, src/xtopcom/xvledger/xvledger.h, src/xtopcom/xvledger/xvtransaction.h, src/xtopcom/xvledger/xvtxindex.h, src/xtopcom/xvledger/xvtxstore.h, tests/xvledger_test/xdummy_blockstore.h
=> opt(blockstore): tackle tx store seperately

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xvledger/src/xvstoreimp.cpp
=> opt(xblockstore): check before decoding txs from block

src/xtopcom/xrpc/xcluster/xcluster_query_manager.cpp, src/xtopcom/xrpc/xcluster/xcluster_query_manager.h, src/xtopcom/xrpc/xgetblock/get_block.cpp
=> feat(rpc): update getAccount, getBlock; add getLatestTables

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvblockhub.h, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xblockstore/src/xvunithub.h, src/xtopcom/xvledger/xvblockstore.h, tests/xvledger_test/xdummy_blockstore.h
=> fix(blockstore): top-3644, index, block flag out of sync

src/libraries/xapplication/src/xapplication.cpp, src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvblockhub.h, src/xtopcom/xblockstore/src/xvunithub.cpp
1. revert changes from xerror to xwarn;
2. add load db step in exist_genesis_block interface;
=> revert changes from xerror to xwarn

src/xtopcom/xBFT/src/xconsdriver.cpp, src/xtopcom/xBFT/src/xconsrules.cpp
=> opt(xbft): add log; polish vote rule

.github/scripts/test_clear.sh, .github/scripts/test_xtop_allinone.sh, .github/workflows/ci.yml
open test flow;
fix event condition, only open & reopen;
=> open ci test flow

.github/workflows/ci.yml
push event will run ci flow now
=> add push event

.github/scripts/test_xtop_allinone.sh
=> support T8000

cmake/gitinfo.cmake, src/libraries/xchaininit/src/version.cpp
`./xtopchain -v`:
```
...
git commit info: 237eb79
git submodule: xtopcom/xbase:ff9eace|xtopcom/xdepends:415349d|xtopcom/xvm:9cba693
...
```
=> perf(build): add git submodule commit info

src/xtopcom/xchain_upgrade/src/xchain_upgrade_center.cpp, src/xtopcom/xchain_upgrade/xchain_upgrade_type.h, src/xtopcom/xcommon/xip.h, src/xtopcom/xtxpool_service_v2/src/xcons_utl.cpp, src/xtopcom/xunit_service/src/xcons_utl.cpp, tests/xchain_upgrade/test_xchain_upgrade.cpp
remove useless forkpoints & unnecessary inheritance & force clear XIP network version.
=> fix(xcommon,xchain_upgrade,txpool,us): code cleanup.

src/libraries/xsync/src/xsync_netmsg_dispatcher.cpp, src/xtopcom/xtxpool_service_v2/src/xtxpool_service.cpp, src/xtopcom/xunit_service/src/xbatch_packer.cpp, src/xtopcom/xunit_service/src/xcons_proxy.cpp, src/xtopcom/xunit_service/src/xcons_service.cpp, src/xtopcom/xunit_service/src/xcons_service_mgr.cpp, src/xtopcom/xunit_service/src/xcons_unorder_cache.cpp, src/xtopcom/xunit_service/src/xleader_election.cpp, src/xtopcom/xunit_service/src/xnetwork_proxy.cpp, src/xtopcom/xunit_service/src/xtableblockservice.cpp, src/xtopcom/xunit_service/src/xtimer_block_maker.cpp, src/xtopcom/xunit_service/src/xtimer_dispatcher.cpp, src/xtopcom/xunit_service/src/xtimer_picker.cpp, src/xtopcom/xunit_service/src/xtimer_service.cpp, src/xtopcom/xunit_service/src/xworkpool_dispatcher.cpp, src/xtopcom/xunit_service/xcons_face.h, src/xtopcom/xunit_service/xunit_log.h
=> fix(xunit_service):add xunit log prefix

src/xtopcom/xdata/xproperty.h, src/xtopcom/xdata/xunit_bstate.h, src/xtopcom/xrpc/xgetblock/get_block.cpp
=> bug(xdata): burn_token return 0

src/xtopcom/xstore/src/xaccount_context.cpp
=> fix(xstore): redeem 0 vote is legal

src/xtopcom/xstore/src/xaccount_context.cpp
=> opt(xstore): uint64_add, uint64_sub support 0

src/libraries/xchaininit/src/xchain_command.cc, src/xtopcom/xrpc/xcluster/xcluster_query_manager.cpp, src/xtopcom/xrpc/xedge/xedge_method_manager.hpp, src/xtopcom/xrpc/xrpc_init.cpp
=> opt(rpc): arc node support rpc query & tx sending

src/libraries/xchaininit/src/xchain_command.cc
=> opt(topio): disable deploy & run contract temporarily

src/xtopcom/xblockmaker/src/xtable_maker.cpp, src/xtopcom/xtxpool_v2/src/xreceipt_state_cache.cpp, src/xtopcom/xtxpool_v2/src/xtxpool_table.cpp, src/xtopcom/xtxpool_v2/xreceipt_state_cache.h
=> feat(txpool/unitservice):table-table txs flow control by receipt id state

.github/workflows/ci.yml
=> add build_ci 

src/libraries/xchaininit/src/xinit.cpp
1. update xbase to 1.3.2
2. add xbase info while process start
=> update xbase to 1.3.2

src/xtopcom/xBFT/test/basic/main.cpp, src/xtopcom/xBFT/test/basic/xtestshard.cpp, src/xtopcom/xBFT/test/common/xtestnode.cpp, src/xtopcom/xBFT/test/common/xtestnode.hpp, src/xtopcom/xcertauth/test/basic/main.cpp, src/xtopcom/xcertauth/test/basic/xunitblock.cpp, src/xtopcom/xcertauth/test/basic/xunitblock.hpp, src/xtopcom/xcrypto/src/xckey.cpp, src/xtopcom/xcrypto/xckey.h, src/xtopcom/xvledger/src/xvcnode.cpp, src/xtopcom/xvledger/xvaccount.h
 1. support account of ETH address format at core layers 
 2. update related test cases
=> support account of ETH address format at core layers

src/xtopcom/xtxexecutor/src/xtransaction_executor.cpp
(cherry picked from commit 50a76895d57bd71bd8c826c45485cdd2a14e3870)
=> fix test crash

src/xtopcom/xdata/src/xblockbuild.cpp
=> bug(xdata): full table should not set full state

src/libraries/xsync/src/xsync_object.cpp, src/xtopcom/xdata/xentire_block.hpp
=> bug(xdata):deserialize result may be null

src/xtopcom/xrpc/xcluster/xcluster_query_manager.cpp, src/xtopcom/xtopcl/src/api_method_imp.cpp
=> opt(topio): top-3800

src/libraries/xchaininit/src/xchain_command.cc, src/xtopcom/xunit_service/src/xtimer_picker.cpp
=> opt(topio, drand): update log, print

src/xtopcom/xBFT/src/xtimercertview.cpp, src/xtopcom/xchain_timer/src/xchain_timer.cpp, src/xtopcom/xmetrics/xmetrics.cpp, src/xtopcom/xmetrics/xmetrics.h, src/xtopcom/xunit_service/src/xbatch_packer.cpp, src/xtopcom/xunit_service/src/xtimer_picker.cpp
=> opt(drand, metric): drand event useless; metric_gauge more efficient

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xvnetwork/src/xvhost.cpp
http://192.168.50.172:8180/browse/TOP-3823
a temp fix for receipt message.
=> feat(xvnetwork): special path for xtxpool_msg_send_receipt & xtxpool_msg_recv_receipt

src/libraries/xsync/src/xchain_downloader.cpp, src/xtopcom/xBFT/src/xconsaccount.cpp, src/xtopcom/xBFT/src/xconscontext.cpp, src/xtopcom/xBFT/src/xconsdriver.cpp, src/xtopcom/xBFT/src/xconsdriver.h, src/xtopcom/xBFT/src/xconsengine.cpp, src/xtopcom/xBFT/src/xconsobj.cpp, src/xtopcom/xBFT/src/xconsrules.cpp, src/xtopcom/xBFT/src/xconsync.cpp, src/xtopcom/xBFT/src/xpacemaker.cpp, src/xtopcom/xBFT/src/xtimercertview.cpp, src/xtopcom/xBFT/xconsengine.h, src/xtopcom/xBFT/xconsobj.h, src/xtopcom/xblockstore/src/xsyncvstore.cpp, src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xvledger/src/xvbindex.cpp, src/xtopcom/xvledger/xvbindex.h
=> merge from taylor' branch

src/xtopcom/xunit_service/src/xleader_election.cpp
http://192.168.50.172:8180/browse/TOP-3905
=> fix(xus): using comprehensive stake.

.github/scripts/notify.sh
send ci result mail to chain & xtest
=> resolve notify email address

src/xtopcom/xnode/src/main.cc, src/xtopcom/xnode/src/main.h
wip, self test ok, needs qa verification
=> opt(topio): top3893, safebox started first

src/xtopcom/xmetrics/xmetrics.cpp, src/xtopcom/xmetrics/xmetrics.h, src/xtopcom/xtxpool_v2/src/xpending_account.cpp, src/xtopcom/xtxpool_v2/src/xtx_receipt_queue.cpp, src/xtopcom/xtxpool_v2/src/xtxmgr_table.cpp, src/xtopcom/xtxpool_v2/src/xtxpool_table.cpp, src/xtopcom/xtxpool_v2/xpending_account.h, src/xtopcom/xtxpool_v2/xtx_queue.h, src/xtopcom/xtxpool_v2/xtx_receipt_queue.h, src/xtopcom/xtxpool_v2/xtxpool_info.h
Reverts telosprotocol/TOP-chain#711
=> Revert "feat(txpool):add metrics and debug log"

scripts/deploy_allinone/config/config.rec1.json, scripts/deploy_allinone/config/config.rec2.json, scripts/deploy_allinone/config/config.rec3.json, scripts/deploy_allinone/config/config.rec4.json, scripts/deploy_allinone/config/config.rec5.json, scripts/deploy_allinone/config/config.rec6.json, scripts/deploy_multi_hosts/run.sh
=> resolve deploy allinone script, skip root hash check

src/xtopcom/xnode/src/main.cc, src/xtopcom/xnode/src/main.h
Reverts telosprotocol/TOP-chain#709
=> Revert "opt(topio): top3893, safebox started first"

.github/scripts/test_xtop_allinone.sh
run some topio cmd must start safebox first, eg: setdefaultaccount.
run some topio cmd will start safebox automatic, eg: listaccounts.
so, change test_xtop_allinone.sh, make sure run listaccounts cmd before setdefaultaccount cmd;
=> resolve ci test script

src/xtopcom/xblockstore/src/xvblockhub.cpp
本地组网运行20分钟，无crash，log示例
/tmp/zec2/xtop.log:xbase-16:41:02.166-T31737:[Keyfo]-(metrics_packet_impl:24): [metrics]{"category":"blockstore","tag":"height_meta","type":"real_time","content":{"account":"T2000138NpRxYCFQxMHvedTxRpgkb8B7oHt235N2W@0","cert":1,"lock":0,"commit":0,"connect":0,"execute":0,"full":0,"genesis_connect":0}}
/tmp/zec2/xtop.log:xbase-16:41:02.166-T31737:[Keyfo]-(metrics_packet_impl:24): [metrics]{"category":"blockstore","tag":"height_meta","type":"real_time","content":{"account":"T2000138JQPo5TcurZsVLFUMd5vHJRBLenLWjLhk6@0","cert":0,"lock":0,"commit":0,"connect":0,"execute":0,"full":0,"genesis_connect":0}}
/tmp/zec2/xtop.log:xbase-16:42:12.156-T31737:[Keyfo]-(metrics_packet_impl:24): [metrics]{"category":"blockstore","tag":"height_meta","type":"real_time","content":{"accoun …
=> opt(blockstore): top-3979, add height meta info

src/xtopcom/xdata/src/xunit_bstate.cpp, src/xtopcom/xdata/xunit_bstate.h, tests/xblockstore2_test/test_create_block.cpp
test ok,
1628044530 = 5485533 * 10 + 1573189200
=> bug(xdata): get_account_create_time return time_stamp instead of clock

src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xvledger/xvblock.h, tests/xblockstore2_test/test_block_executed.cpp
unit test: 
1. store 5 tableblock, write_index_to_db call reduced from 17 to 14
2. inorder store_block ok
3. disorder store_block ok
=> （WIP）blockstore(opt): top-3981, delete execute flag

src/xtopcom/xBFT/src/xconsaccount.cpp, src/xtopcom/xBFT/xconsaccount.h, src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvgenesis.cpp, src/xtopcom/xvledger/xvblock.h
=> opt(blockstore): 4005, delete block connect flag

src/libraries/xelect/client/xelect_client.h, src/libraries/xelect/src/xelect_client.cpp, src/xtools/xaction_param_parse/src/xaction_param_parse.cpp, src/xtopcom/xdata/src/xtransaction.cpp, src/xtopcom/xdata/xaction.h, src/xtopcom/xdata/xdatautil.h, src/xtopcom/xdata/xtransaction.h, src/xtopcom/xrpc/xedge/xedge_method_manager.hpp, src/xtopcom/xrpc/xgetblock/get_block.cpp, src/xtopcom/xrpc/xuint_format.h, src/xtopcom/xtopcl/src/protocol.cpp, src/xtopcom/xtopcl/src/task/task_dispatcher.cpp, src/xtopcom/xtopcl/src/xcrypto.cpp, src/xtopcom/xverifier/src/xverifier_utl.cpp
topio send tx, querytx ok
bootstrap node join ok
=> tx(refactor): move tx_to_json & json_to_tx to xtransaction_t

src/libraries/xapplication/src/xapplication.cpp, src/libraries/xsync/src/xchain_downloader.cpp, src/libraries/xsync/src/xdownloader.cpp, src/libraries/xsync/src/xsync_object.cpp, src/libraries/xsync/src/xsync_range_mgr.cpp, src/libraries/xsync/src/xsync_store.cpp, src/libraries/xsync/src/xsync_store_shadow.cpp, src/libraries/xsync/src/xsync_task.cpp, src/libraries/xsync/src/xsync_util.cpp, src/libraries/xsync/xchain_downloader.h, src/libraries/xsync/xdownloader.h, src/libraries/xsync/xsync_object.h, src/libraries/xsync/xsync_range_mgr.h, src/libraries/xsync/xsync_store.h, src/libraries/xsync/xsync_store_shadow.h, src/libraries/xsync/xsync_task.h, src/xtopcom/xblockstore/src/xvblockhub.cpp, src/xtopcom/xblockstore/src/xvblockhub.h, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xblockstore/src/xvunithub.h, src/xtopcom/xvledger/src/xvdbkey.cpp, src/xtopcom/xvledger/xvblockstore.h, src/xtopcom/xvledger/xvdbkey.h, tests/xvledger_test/xdummy_blockstore.h
feat(xsync): shift overflow
feat(xsync): fast sync leak one block
feat(xsync): plus overflow
feat(xsync): stack overflow
feat(xsync): sync blocks out of the specified interval of height
feat(xsync): access null pointer
=> feat(xsync): refactor genesis connect height

src/xtopcom/xblockmaker/src/xproposal_maker.cpp
(cherry picked from commit df35fa4b98d80c7e26b907b2c9b426a90ed247c6)
=> TOP-4034 fix shard contract sync issue

src/libraries/xelect/src/xelect_client.cpp, src/xtopcom/xdata/src/xtransaction.cpp, src/xtopcom/xdata/xaction.h, src/xtopcom/xdata/xcons_transaction.h, src/xtopcom/xdata/xtransaction.h, src/xtopcom/xrpc/xedge/xedge_local_method.h, src/xtopcom/xrpc/xedge/xedge_local_method.hpp, src/xtopcom/xrpc/xgetblock/get_block.cpp, src/xtopcom/xrpc/xrule_manager.cpp, src/xtopcom/xtopcl/include/api_method_imp.h, src/xtopcom/xtopcl/src/api_method_imp.cpp, src/xtopcom/xtxexecutor/src/xtransaction_context.cpp, src/xtopcom/xtxexecutor/xtransaction_context.h
create user account; transfer; run_contract; pledge token  tgas; redeem token tgas; pledge token vote; redeem token vote; vote; abolish_vote;
all basic self test ok
query_tx ok
"tx_action" : {
"receiver_action" : {
"action_authorization" : "",
"action_ext" : "",
"action_hash" : 0,
"action_name" : "",
"action_param" : "0x2e00000054383030303033376434666263303862663435313361363861323837656432313862306164626434393765663330",
"action_size" : 124,
"action_type" : 2,
"tx_receiver_account_addr" : "T8000037d4fbc08bf4513a68a287ed218b0adbd497ef30"
},
"sender_action" : {
"action_authorization" : "",
"action_ext" : "",
"action_hash" : 0,
"action_name" : "",
"action_param" : "",
"action_size" : 74,
"action_type" : 1,
"tx_sender_account_addr" : "T8000037d4fbc08bf4513a68a287ed218b0adbd497ef30"
}
},
=> tx(refactor): delete useless code

src/xtopcom/xtopcl/include/api_method.h, src/xtopcom/xtopcl/src/api_method.cpp
=> bug(topio): top-3974, queryminerreward

src/libraries/xapplication/src/xapplication.cpp, src/xtopcom/xdata/src/xtransaction_v1.cpp, src/xtopcom/xdata/src/xtransaction_v2.cpp, src/xtopcom/xdata/xtransaction.h, src/xtopcom/xdata/xtransaction_v1.h, src/xtopcom/xdata/xtransaction_v2.h, src/xtopcom/xdata/xtx_factory.h, src/xtopcom/xrpc/prerequest/xpre_request_data.cpp, src/xtopcom/xrpc/xcluster/xcluster_query_manager.cpp, src/xtopcom/xrpc/xedge/xedge_method_manager.hpp, src/xtopcom/xrpc/xgetblock/get_block.cpp, src/xtopcom/xrpc/xgetblock/get_block.h, src/xtopcom/xrpc/xrpc_method.h, src/xtopcom/xrpc/xrule_manager.cpp, src/xtopcom/xtopcl/include/api_method.h, src/xtopcom/xtopcl/include/api_method_imp.h, src/xtopcom/xtopcl/include/global_definition.h, src/xtopcom/xtopcl/include/task/task_info.h, src/xtopcom/xtopcl/src/api_method.cpp, src/xtopcom/xtopcl/src/api_method_imp.cpp, tests/xdata_test/test_tx_v2.cpp
=> opt(tx v2): rpc update

src/libraries/xapplication/src/xbeacon_chain_application.cpp, src/libraries/xelect/src/xelect_client_process.cpp, src/xtopcom/xbasic/xproper_fraction.hpp, src/xtopcom/xdata/src/xstandby_data_struct.cpp, src/xtopcom/xdata/src/xstandby_node_info2.cpp, src/xtopcom/xdata/xcodec/xmsgpack/xstandby_node_info2_codec.hpp, src/xtopcom/xdata/xnative_contract_address.h, src/xtopcom/xdata/xregistration/xregistration_node_info.h, src/xtopcom/xdata/xstandby/xstandby_data_struct.h, src/xtopcom/xdata/xstandby/xstandby_node_info2.h, tests/xsystem_contract/xelect_contract/src/xtest_zec_elect_consensus_contract.cpp, tests/xsystem_contract/xelection_algorithm/fixture/xtest_elect_group_contract_fixture.cpp, tests/xsystem_contract/xelection_algorithm/fixture/xtest_election_data_manager_fixture.cpp, tests/xsystem_contract/xelection_algorithm/src/xtest_elect_consensus_group_in_and_out_number.cpp, tests/xsystem_contract/xelection_algorithm/src/xtest_elect_nonsensus_group.cpp, tests/xsystem_contract/xelection_algorithm/src/xtest_election_group_shrink.cpp, tests/xsystem_contract/xelection_algorithm/xtest_elect_group_contract_fixture.h, tests/xsystem_contract/xelection_algorithm/xtest_election_data_manager_fixture.h
=> enable zec elect edge archive

README.md, src/xtopcom/xdata/src/xtransaction_v2.cpp, src/xtopcom/xrpc/xgetblock/get_block.cpp
self test ok
basic regression test ok, no tx hash error
=> opt(tx): refactor

src/libraries/xchaininit/src/xinit.cpp, src/xtopcom/xblockmaker/src/xproposal_maker.cpp, src/xtopcom/xmetrics/metrics_handler/basic_handler.cpp, src/xtopcom/xmetrics/metrics_handler/basic_handler.h, src/xtopcom/xmetrics/metrics_handler/timer_handler.cpp, src/xtopcom/xmetrics/metrics_handler/xmetrics_packet_info.cpp, src/xtopcom/xmetrics/xmetrics.cpp, src/xtopcom/xmetrics/xmetrics.h, src/xtopcom/xunit_service/src/xbatch_packer.cpp, src/xtopcom/xunit_service/src/xcons_unorder_cache.cpp
add metrics log and change XMETRICS_PACKET_INFO to log.
=> feat(metrics):add metrics log and change XMETRICS_PACKET_INFO to log.

CMakeLists.txt, build_options.sh, src/xtopcom/xelect_net/src/elect_netcard.cc, src/xtopcom/xtransport/src/xudp_socket.cc, src/xtopcom/xwrouter/src/xwrouter.cc
set p2pbroadcast defaultly xinfo log
=> add p2p_bendwidth build option.

src/xtopcom/xrpc/xgetblock/get_block.cpp
=> feature(rpc): getBlock return parent height

src/xtopcom/xmetrics/xmetrics.cpp, src/xtopcom/xmetrics/xmetrics.h, src/xtopcom/xunit_service/src/xbatch_packer.cpp, src/xtopcom/xunit_service/src/xtimer_picker.cpp, src/xtopcom/xutility/src/xhash.cpp, src/xtopcom/xvledger/xmerkle.hpp, tests/xdata_test/test_genesis_block.cpp, tests/xmetrics/test_metrics.cpp
2.delete useless metrics's index.
3.add error code's count.
4.add unit test case.
5.add merkle hash count.
=> 1.add three type of transaction success.

src/xtopcom/xvledger/src/xvblock.cpp
1.add xvblock hash metrics.
2.optimize xvblock hash.
=> feat(xvblock):optimize xvblock hash

src/libraries/xapplication/src/xcons_mgr_builder.cpp, src/libraries/xapplication/xcons_mgr_builder.h, src/xtopcom/xBFT/src/xconscontext.cpp, src/xtopcom/xBFT/src/xconsdriver.cpp, src/xtopcom/xBFT/src/xtimercertview.cpp, src/xtopcom/xblockmaker/src/xtable_maker.cpp, src/xtopcom/xcertauth/src/xcertauth.cpp, src/xtopcom/xvledger/src/xvblockbuild.cpp, src/xtopcom/xvledger/xvblock_fork.h, src/xtopcom/xvledger/xvblockbuild.h, src/xtopcom/xvledger/xvcertauth.h, tests/mock/xmock_auth.hpp, tests/xblockmaker_test/test_common.hpp
feat(hash):1、xvblock hash optimized.2、merkle tree hash optimized.
=> feat(hash):1、xvblock hash optimized.2、merkle tree hash optimized.

src/xtopcom/xBFT/src/xconsdriver.cpp, src/xtopcom/xblockstore/src/xvblockdb.cpp, src/xtopcom/xdata/src/xblock.cpp, src/xtopcom/xunit_service/src/xbatch_packer.cpp, src/xtopcom/xvledger/src/xvblock.cpp, src/xtopcom/xvledger/xvblock.h, tests/xblockmaker_test/test_tablemaker.cpp
=> feat(block):optimize block serialize.

src/xtopcom/xdb/src/xdb_rocksdb.cpp
=> New horizions 1.2.7 rocksdb

src/xtopcom/xdb/src/xdb_rocksdb.cpp
xdb_impl::init,db_root_dir=/tmp/con1/db_v3,memory Totalram 17179869184, Available: 0.cache_type:1
total ram 16GB, Mac no need to print free ram, cache type 1 ok
=> opt(db): macos compatible issue

src/libraries/xsync/src/xchain_block_fetcher.cpp, src/libraries/xsync/src/xrole_chains.cpp, src/libraries/xsync/src/xsync_handler.cpp, src/libraries/xvnode/src/xvnode.cpp, src/xtopcom/xblockstore/src/xvblockpruner.cpp
sync;2)just storage node support reliable sync; 3)drand prune range at
least 128
=> feat(fullnode): 1) drand account in fullnode just support checkpoint

src/libraries/xgrpc_mgr/src/xgrpc_mgr.cpp, src/xtopcom/xblockstore/src/xvunithub.cpp, src/xtopcom/xrpc/xgetblock/get_block.cpp
=> ID1001851 & ID1001845

src/xtopcom/xtxpool_service_v2/src/xtxpool_service.cpp, src/xtopcom/xtxpool_service_v2/src/xtxpool_service_mgr.cpp, src/xtopcom/xtxpool_service_v2/xtxpool_service.h, src/xtopcom/xtxpool_service_v2/xtxpool_service_face.h
timely refresh tables of txpool services which are not unreged.
=> fix(txpool):fix ID1001869

src/libraries/xapplication/src/xapplication.cpp, src/libraries/xchaininit/src/xchain_command.cc, src/xtopcom/xnode/src/main.cc, src/xtopcom/xnode/src/main.h, src/xtopcom/xvledger/src/xvledger.cpp, src/xtopcom/xvledger/xvledger.h, tests/xdb/CMakeLists.txt, tests/xdb/test_performance.cpp
add compress params and unit test.
=> [feat]add compress params and unit test.

src/xtools/xdb_export/src/main.cpp, src/xtools/xdb_export/src/xdb_export.cpp, src/xtools/xdb_export/xdb_export.h
add compress params and unit test.
=> fix db query sync info.

src/xtopcom/xblockmaker/src/xrelay_proposal_maker.cpp, src/xtopcom/xdata/src/xrelay_block.cpp, src/xtopcom/xdata/src/xrelay_block_store.cpp, src/xtopcom/xdata/xrelay_block.h, src/xtopcom/xdata/xrelay_block_store.h, src/xtopcom/xrpc/xrpc_eth_query_manager.cpp
=> 1.fix  timeout check ;

src/xtopcom/xcommon/src/xaccount_base_address.cpp, src/xtopcom/xcommon/src/xnode_id.cpp, src/xtopcom/xcommon/src/xtable_id.cpp, src/xtopcom/xcommon/xaccount_base_address.h, src/xtopcom/xcommon/xnode_id.h, tests/xcommon/src/test_account_address.cpp
1. revert PR 95af711aa90f0fcb34056e56e95bb5549ece23ba
2. add UT for validating xaccount_address_t's size
=> remove xvaccount member from xaccount_address_t

src/xtopcom/xevm_contract_runtime/src/xdelegate_eth_contract.cpp, src/xtopcom/xevm_contract_runtime/src/xdelegate_top_contract.cpp, src/xtopcom/xevm_contract_runtime/src/xdelegate_usdc_contract.cpp, src/xtopcom/xevm_contract_runtime/src/xdelegate_usdt_contract.cpp, tests/xevm_engine_test/test_cases/delegate_erc20/delegate_erc20.json
This reverts commit f6af5dbe01c098d8273dd69d5069d381dc829124, reversing changes made to 88621230b9491741009c023f6bcb026bab1b79d6.
=> Revert "Merge pull request #1729 from PaytonWu/dev/v1.7_i3"

src/xtopcom/xevm_common/src/trie/xtrie_sync.cpp, src/xtopcom/xevm_common/trie/xtrie_sync.h, src/xtopcom/xstate_sync/src/xstate_downloader_executer.cpp, src/xtopcom/xstate_sync/src/xstate_sync.cpp, src/xtopcom/xstate_sync/xstate_downloader_executer.h, src/xtopcom/xstate_sync/xstate_sync.h
1. replace sync raw ptr with shared_ptr;
2. replace list with queue;
=> trie sync optimize

src/xtopcom/xstate_sync/src/xstate_downloader.cpp, src/xtopcom/xstate_sync/src/xstate_downloader_executer.cpp, src/xtopcom/xstate_sync/src/xstate_sync.cpp, src/xtopcom/xstate_sync/xstate_downloader_executer.h, src/xtopcom/xstate_sync/xstate_sync.h, tests/xstate_mpt/test_state_mpt.cpp, tests/xstate_sync/test_state_downloader_executer.cpp
1. fix move in lambda
2. add state mpt ut check
=> fix momory leak

src/xtopcom/xrpc/eth_rpc/eth_error_code.h, src/xtopcom/xrpc/xedge/xedge_evm_method_manager.hpp, src/xtopcom/xrpc/xrpc_eth_query_manager.cpp
=> fix: update error code

tests/xsync/archive/main.cpp, tests/xsync/archive/test_xsync_peerset.cpp
=> fix sync UT
